package com.foodie.app.controller;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.security.test.context.support.WithMockUser;
import org.springframework.test.web.servlet.MockMvc;

import java.util.UUID;

import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.redirectedUrl;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
class AdminCategoryCrudControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Test
    @WithMockUser(username = "admin@foodie.com", roles = "ADMIN")
    void addCategoryShouldRedirectSuccessfully() throws Exception {
        String categoryName = "Test Category " + UUID.randomUUID();

        mockMvc.perform(post("/admin/categories/add")
                        .with(csrf())
                        .param("name", categoryName)
                        .param("description", "Generated by CRUD test")
                        .param("imageUrl", "/images/categories/test.jpg"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/admin/categories"));
    }

    @Test
    @WithMockUser(username = "admin@foodie.com", roles = "ADMIN")
    void updateCategoryShouldRedirectSuccessfully() throws Exception {
        mockMvc.perform(post("/admin/categories/update/1")
                        .with(csrf())
                        .param("name", "Updated Category")
                        .param("description", "Updated description")
                        .param("imageUrl", "/images/categories/updated.jpg")
                        .param("isActive", "true"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/admin/categories"));
    }

    @Test
    @WithMockUser(username = "admin@foodie.com", roles = "ADMIN")
    void deleteCategoryShouldRedirectSuccessfully() throws Exception {
        mockMvc.perform(post("/admin/categories/delete/1")
                        .with(csrf()))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/admin/categories"));
    }
}
